modLoader="javafml" 
loaderVersion="[39,)" 
license="All rights reserved"
issueTrackerURL="https://github.com/Caltinor/Project-MMO-2.0/issues/"

[[mods]]
modId="pmmo"
version="${file.jarVersion}"
displayName="Project MMO"
logoFile="star.png"
credits="MMD were there when this mod needed them, including the start"
authors="Harmonised"
description='''
Adds many different skills and benefits thanks to the skills to the game!
'''

[[dependencies.pmmo]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40.1.67,)"
    ordering="NONE"
    side="BOTH"  #this might get changed to server only.

[[dependencies.pmmo]]
    modId="minecraft"
    mandatory=true
	versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
